site_name: linux-documentation

copyright: Главная документация по Linux

repo_url: https://github.com/pannikita/linux-documentation
edit_uri: edit/main/docs/

plugins:
  - search
  - git-committers:
      repository: pannikita/linux-documentation
      branch: main

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
